### ISSUE TITLE
Update config syntax for imposed displacement

### ISSUE THREAD

**Issue by floiseau** [floiseau/fragma#10]
Instead of writing
```toml
[loading.u_imp_max]
left_0 = 0
left_1 = 0
right_0 = 0.1
```
we want to use the array in toml
```toml
[loading.u_imp_max]
left = [0, 0]
right = [0, nan]
```
Here, the `nan` means that we impose nothing on this displacement component (keep the dof free).
