### ISSUE TITLE
Add computation of reaction forces

### ISSUE THREAD

**Issue by floiseau** [floiseau/fragma#14]
The code must compute the reaction forces on the surfaces specified in the parameter file. Those surfaces are specified in the file as:
```toml
[postprocess]
reaction_forces = ["surface_1", "surface_2"]
```
where surface_1 and surface_2 are two specified boundary surfaces.
