### ISSUE TITLE
Add the G-theta method as a postprocess

### ISSUE THREAD

**Issue by floiseau** [floiseau/fragma#33]
In the configuration file, I could add a post-processor with the following parameters
```toml
[postprocess.g_theta]
S_in = ...
S_out = ...
```
The integration region should be specified from the mesh file.

In order to derive the theta field, the method presented in this [newfrac course]( https://gitlab.com/newfrac/CORE-school/newfrac-core-numerics/-/blob/master/02-LEFM.ipynb)
